# MNIST - DNN with Keras
Author: Clênio Eduardo

In [108]:
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense

In [109]:
data = pd.read_csv("train.csv")
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [110]:
pixels = data.iloc[:,1:784].values
labels = data.iloc[:,0:1].values

In [111]:
pixels


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [112]:
pixels = pixels.tolist()
labels = labels.tolist()

training = []
output_list = [0] * 10

for i in range(len(labels)):
    output_row = list(output_list)
    output_row[labels[i][0]] = 1
    training.append([pixels[i], output_row])
    


In [113]:
random.shuffle(training)
training = np.array(training)

train_x = list(training[:,0])
train_y = list(training[:,1])

train_x = np.array(train_x)
train_y = np.array(train_y)

print("Train_x",train_x)
print("Train_y",train_y)

Train_x [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Train_y [[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]
 ...
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 1 ... 0 0 0]]


In [114]:
model = Sequential()
model.add(Dense(100, input_dim=len(train_x[0]), activation='relu'))
model.add(Dense(len(train_y[0]), activation='softmax'))


model.compile(loss='categorical_crossentropy', optimizer='RMSprop', metrics=['accuracy'])

model.fit(train_x, train_y, batch_size=256, epochs=150)

Epoch 1/150
42000/42000 [==============================] - 2s 36us/step - loss: 9.1792 - acc: 0.4267
Epoch 2/150
42000/42000 [==============================] - 1s 20us/step - loss: 7.8599 - acc: 0.5097
Epoch 3/150
42000/42000 [==============================] - 1s 21us/step - loss: 7.1620 - acc: 0.5535
Epoch 4/150
42000/42000 [==============================] - 1s 20us/step - loss: 7.0662 - acc: 0.5596
Epoch 5/150
42000/42000 [==============================] - 1s 20us/step - loss: 6.9846 - acc: 0.5649
Epoch 6/150
42000/42000 [==============================] - 1s 19us/step - loss: 6.9802 - acc: 0.5652
Epoch 7/150
42000/42000 [==============================] - 1s 21us/step - loss: 6.9136 - acc: 0.5697
Epoch 8/150
42000/42000 [==============================] - 1s 21us/step - loss: 6.8941 - acc: 0.5709
Epoch 9/150
42000/42000 [==============================] - 1s 20us/step - loss: 6.8674 - acc: 0.5728
Epoch 10/150
42000/42000 [==============================] - 1s 21us/step - loss: 6.8282 - a

42000/42000 [==============================] - 1s 18us/step - loss: 0.4030 - acc: 0.9740
Epoch 82/150
42000/42000 [==============================] - 1s 18us/step - loss: 0.3730 - acc: 0.9759
Epoch 83/150
42000/42000 [==============================] - 1s 18us/step - loss: 0.4135 - acc: 0.9732
Epoch 84/150
42000/42000 [==============================] - 1s 18us/step - loss: 0.3844 - acc: 0.9752
Epoch 85/150
42000/42000 [==============================] - 1s 18us/step - loss: 0.3977 - acc: 0.9744
Epoch 86/150
42000/42000 [==============================] - 1s 18us/step - loss: 0.3906 - acc: 0.9747
Epoch 87/150
42000/42000 [==============================] - 1s 18us/step - loss: 0.4103 - acc: 0.9736
Epoch 88/150
42000/42000 [==============================] - 1s 18us/step - loss: 0.3652 - acc: 0.9765
Epoch 89/150
42000/42000 [==============================] - 1s 18us/step - loss: 0.3670 - acc: 0.9764
Epoch 90/150
42000/42000 [==============================] - 1s 18us/step - loss: 0.3801 - acc: 

In [115]:
data2= pd.read_csv("test.csv")
data2.head()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 784 columns]

In [116]:
teste = data2.iloc[:,0:783].values

In [117]:
teste

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [118]:
prediction = model.predict(teste, batch_size=1, verbose=0)

In [119]:
print(prediction)

[[0. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 1. ... 0. 0. 0.]]
